config/routes.rb
Rails.application.routes.draw do
  get '/' => "homes#top"
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
  @book = Book.new
  @books = Book.all
  end
    def create

  @books = Book.all
   @book = Book.new(book_params)
   if @book.save
   redirect_to book_path(@book.id),flash: { notice: 'Book was successfully created.' }
    else
      render :index
  end
end
  def show
     @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])

  end
  def update
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),flash: { notice: 'Book was successfully updated.' }
     else
      render :edit
  end
  end
    def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除

    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end
    private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, local:true do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

<div>  <%= f.submit 'Update Book' %> </div>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
<thead>
<tr>
<th> <h4>Title</h4> </th>
<th> <h4>Body</h4> </th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr> <td> <span><%= book.title %></span> </td>

 <td> <span><%= book.body %></span> </td>

  <td> <%= link_to "Show", book_path(book.id) %> </td>
  <td>  <%= link_to "Edit", edit_book_path(book.id) %> </td>
  <td> <%= link_to "Destroy",book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %> </td>
  </tr>
</tbody>
<% end %>
</table>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2>New book</h2>

<%= form_with model: @book, local:true do |f| %>

  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

<div>
  <%= f.submit 'Create Book' %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p>
<strong>Title:</strong>
<%= @book.title %>
</p>

<p>
<strong>Body:</strong>
<%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <storong>
    Bookers
  </storong>
  へ!
</h1>
<p><strong>Bookers</strong>
ではさまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
<%= link_to "start",books_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>